package:
  name: pbhoney
  version: 15.8.24

source:
  git_url: https://github.com/shokrof/pbhoney.git
#  git_tag: v15.8.24



requirements:
  host:
    - python 2.7

  run:
    - python
    - samtools 0.1.19
    - blasr
    - h5py 2.10
    - pysam 0.8
    - pbdagcon
    - numpy
    - networkx
    - intervaltree_bio


about:
  home: https://github.com/shokrof/pbhoney
 